name: Test GitHub Action

on:
  push:
    paths:
      - '**'
      - '.github/workflows/test-action.yml'
  pull_request:
    paths:
      - '**'
      - '.github/workflows/test-action.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo base_branch and target_branch
        run: |
          echo "Base branch: ${{ github.event.repository.default_branch }}"
          echo "Target branch: ${{ github.ref_name }}"
          echo "Model: ${{ env.MODEL }}"

      - name: Run custom action
        uses: ./
        with:
          apikey: ${{ secrets.APIKEY }}
          apiendpoint: ${{ secrets.APIENDPOINT }}
          model: ${{ env.MODEL }}
          base_branch: ${{ github.event.repository.default_branch }}
          target_branch: ${{ github.ref_name }}